

//list products
export const PRODUCT_LIST_START = 'PRODUCT_LIST_START';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE ='PRODUCT_LIST_FAILURE';

//single product
export const GET_PRODUCT_START = 'PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';